### ISSUE TITLE
failure on my windows 10 wsl2 

### ISSUE THREAD

**Issue by shelper** [Rucadi/wsld#2]
when i run 
`wsld.exe -d debian_d -i debian`
i got 
```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at wsld_cs.Docker.DownloadImage()
   at wsld_cs.Docker.InstallWsldImage()
   at wsld_cs.Program.Main(String[] args)
```
same error for other docker images too

**Comment by Rucadi** [comment]
Hi!

Thanks for trying it out! Until July I will not be able to look into these things :( 

I only tried this tool with the Windows preview versions, and I will rewrite the functionality and implement more options in mid-July or so, I hope that I'll able fix your problem. 

If you don't care, I'll get back to you when I make these changes, meanwhile, if you find a way to get it working, share it :)

**Comment by Rucadi** [comment]
Hello @shelper ! I updated wsld, so I would love if you check it out :)  Some functionality might be missing right now, but I'll be integrating the missing changes in future updates.
